services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: usuario
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql