ALTER TABLE Clientes
MODIFY COLUMN NombreCliente VARCHAR(45),
MODIFY COLUMN ApellidosCliente VARCHAR(30),
MODIFY COLUMN DireccionCliente VARCHAR(30),
MODIFY COLUMN Poblacion VARCHAR(15),
MODIFY COLUMN CodigoPostal VARCHAR(5),
MODIFY COLUMN Provincia VARCHAR(15),
MODIFY COLUMN Telefono VARCHAR(10),
MODIFY COLUMN FechaNacimiento DATE;

