ALTER TABLE Clientes
MODIFY COLUMN NombreCliente VARCHAR(15),
MODIFY COLUMN ApellidosCliente VARCHAR(30),
MODIFY COLUMN DireccionCliente VARCHAR(30),
MODIFY COLUMN Poblacion VARCHAR(15),
MODIFY COLUMN CodigoPostal VARCHAR(5),
MODIFY COLUMN Provincia VARCHAR(15) DEFAULT 'Valencia',
MODIFY COLUMN Telefono VARCHAR(10),
MODIFY COLUMN FechaNacimiento DATE;

ALTER TABLE CochesVendidos
MODIFY COLUMN Matricula VARCHAR(7) NOT NULL,
MODIFY COLUMN Marca VARCHAR(15),
MODIFY COLUMN Modelo VARCHAR(20),
MODIFY COLUMN Color VARCHAR(12),
MODIFY COLUMN Precio DECIMAL(10,2),